### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Emiluren** [alda-lang/alda-sound-engine-clj#13]
So I tried to run alda and play some notes but I don't hear anything (also I get an error about constructing terminal which can be worked around by setting [TERM=xterm-color](https://github.com/lihaoyi/mill/issues/139))

```
~/P/alda (master|…) $ bin/alda repl
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
	at jline.TerminalFactory.create(TerminalFactory.java:102)
	at jline.TerminalFactory.get(TerminalFactory.java:186)
	at jline.TerminalFactory.get(TerminalFactory.java:192)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:243)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:235)
	at jline.console.ConsoleReader.<init>(ConsoleReader.java:223)
	at alda.repl.AldaRepl.<init>(AldaRepl.java:71)
	at alda.Main.main(Main.java:258)

 █████╗ ██╗     ██████╗  █████╗
██╔══██╗██║     ██╔══██╗██╔══██╗
███████║██║     ██║  ██║███████║
██╔══██║██║     ██║  ██║██╔══██║
██║  ██║███████╗██████╔╝██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝

          1.0.0-rc81
         repl session

Type :help for a list of available commands.

> piano: c
p> 
```

**Comment by Emiluren** [comment]
Playing from a file also doesn't work
```
~/P/alda (master|…) $ echo "bassoon: o2 d8 e (quant 30) f+ g (quant 99) a2" > test.alda
~/P/alda (master|…) $ alda play --file test.alda
[27713] Parsing/evaluating...
[27713] Playing...
```

I should probably say that I am running Arch Linux

**Comment by daveyarwood** [comment]
I read in a comment on the issue you linked that the "Failed to construct terminal" issue can be solved by upgrading JLine to 2.14.4+. I'll cut a new release of Alda that has a newer version of JLine, and hopefully that should fix it. (EDIT: Alda 1.0.0-rc82 is out with this fix.)

Off-hand, I'm not sure why you might not be hearing sound... it could be for a number of reasons. What version of Java are you running? (i.e. what's the output of `java -version`?)

**Comment by Emiluren** [comment]
```
➜  ~ java -version
openjdk version "1.8.0_172"
OpenJDK Runtime Environment (build 1.8.0_172-b11)
OpenJDK 64-Bit Server VM (build 25.172-b11, mixed mode)
```

the package I have installed is 
```
extra/jdk8-openjdk 8.u172-2 (8.2 MiB 38.0 MiB) (Installed)
    OpenJDK Java 8 development kit
```

**Comment by Emiluren** [comment]
Unrelated but I also opened [an issue about the server version error message](https://github.com/alda-lang/alda-client-java/issues/36). It may be unnecessary but I just thought I'd make a note of it.

**Comment by daveyarwood** [comment]
Closing this issue as it isn't clearly related to Alda. I'm happy to help troubleshoot further if possible!
